# Generated by Django 4.1.2 on 2022-11-10 16:46

from django.db import migrations, models
import nosotros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('titulo', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to=nosotros.models.upload_path)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('titulo', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to=nosotros.models.upload_path)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=1)),
                ('calle', models.CharField(blank=True, max_length=500, null=True)),
                ('tlf', models.CharField(blank=True, max_length=500, null=True)),
                ('correo', models.EmailField(blank=True, max_length=500, null=True)),
                ('mapa', models.URLField()),
            ],
        ),
    ]
