# Generated by Django 4.1.2 on 2022-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_autoridad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
