# Generated by Django 4.1.2 on 2022-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_preguntasfrecuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('lugar', models.CharField(max_length=500)),
                ('requisitos', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('expiracion', models.DateField()),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
