# Generated by Django 4.1.2 on 2022-11-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_departamento_oficina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoridad',
            old_name='descrpcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
