# Generated by Django 4.1.2 on 2022-11-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0003_equipo_slug_alter_autoridad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='imagen',
            field=models.ImageField(upload_to='nosotros/autoridades'),
        ),
    ]
