# Generated by Django 4.1.2 on 2022-11-06 16:03

from django.db import migrations, models
import nosotros.models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0004_rename_descripcion_autoridad_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='imagen',
            field=models.ImageField(upload_to=nosotros.models.upload_path),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(upload_to=nosotros.models.upload_path),
        ),
    ]
