# Generated by Django 4.1.2 on 2022-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marco_normativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='año',
        ),
        migrations.AddField(
            model_name='convenio',
            name='final',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='año',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='edicto',
            name='año',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='leyesydecreto',
            name='año',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='año'),
        ),
    ]
