# Generated by Django 4.1.2 on 2022-11-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marco_normativo', '0002_acuerdos_convenios_edictos_flujograma'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edictos',
            new_name='Acuerdo',
        ),
        migrations.RenameModel(
            old_name='Competencias',
            new_name='Competencia',
        ),
        migrations.RenameModel(
            old_name='Acuerdos',
            new_name='Convenio',
        ),
        migrations.RenameModel(
            old_name='Convenios',
            new_name='Edicto',
        ),
        migrations.RenameModel(
            old_name='LeyesYDEcretos',
            new_name='LeyesYDecreto',
        ),
    ]
