version: '3.4'

services:
  # db:
  #   restart: always
  #   #restart: unless-stopped
  #   image: postgres:14.1-alpine3.15
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - 5431:5432 
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  django:
    restart: always
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: 
    #   sh -c "python manage.py runserver 0.0.0.0:8000"
    # &&  127.0.0.1:8080"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # environment:
    #   - DB_NAME=
    #   - DB_USER=
    #   - DB_PASSWORD=
    #   - DB_HOST=

  frontend:
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_URL_BACKEND=http://localhost:8000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - django



