version: '3.4'

services:
  frontend:
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/frontned
  db:
    restart: always
    #restart: unless-stopped
    image: postgres:14.1-alpine3.15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5431:5432 
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - ALLOWED_HOSTS=127.0.0.1, localhost
      - DJANGO_KEY=*

    volumes:
      - .:/backend
    depends_on:
      - db


