FROM python:3.10.4-alpine3.15

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN  apk update \
  && apk add gcc musl-dev postgresql-dev python3-dev jpeg-dev zlib-dev \
  && pip install --upgrade pip


COPY ./requirements-docker.txt ./
RUN python -m pip install -r requirements-docker.txt  

COPY ./ ./

#EXPOSE 8000

# RUN python manage.py migrate

CMD [ "sh", "entrypoint.sh" ]
# CMD [ "python", "manage.py", "runserver", "0.0.0.0."]