# Generated by Django 4.1.2 on 2022-11-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='resolucion',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='publicaciones.categoriasresoluciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='año',
            field=models.IntegerField(default=2020, max_length=4),
        ),
    ]
