# Generated by Django 4.1.2 on 2022-11-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import paginas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('icono', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=paginas.models.upload_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('posicion', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('posicion', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='paginas.seccion')),
            ],
        ),
    ]
