# Generated by Django 4.1.2 on 2022-10-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('icono', models.TextField()),
                ('url_source', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('posicion', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='SubTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('icono', models.TextField()),
                ('posicion', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.seccion')),
            ],
        ),
    ]
