# Generated by Django 4.1.2 on 2022-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='url_source',
            field=models.CharField(max_length=500),
        ),
    ]
