# Generated by Django 4.1.2 on 2022-10-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_seccion_url_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='icono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='url_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
