# Generated by Django 4.1.2 on 2022-10-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_seccion_icono_alter_seccion_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitulo',
            old_name='titulo',
            new_name='sub_titulo',
        ),
    ]
