# Generated by Django 4.1.2 on 2022-11-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_rename_titulo_subtitulo_sub_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('icono', models.TextField()),
                ('contenido', models.TextField()),
                ('posicion', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.seccion')),
            ],
        ),
        migrations.DeleteModel(
            name='SubTitulo',
        ),
    ]
