# Generated by Django 4.1.2 on 2022-11-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_contenido_delete_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='url_source',
        ),
        migrations.AddField(
            model_name='seccion',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='paginas.seccion'),
        ),
    ]
