# Generated by Django 4.1.2 on 2022-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_remove_seccion_url_source_seccion_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
