# Generated by Django 4.1.2 on 2022-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_alter_seccion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='icono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
