# Generated by Django 4.1.2 on 2022-11-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_alter_contenido_contenido_alter_contenido_icono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='contenido',
            new_name='text',
        ),
    ]
