# Generated by Django 4.1.2 on 2022-11-06 16:03

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_rename_contenido_contenido_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=paginas.models.upload_path),
        ),
    ]
