# Generated by Django 4.1.2 on 2022-11-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
                ('imagen_principal', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='entradas.noticias')),
            ],
        ),
    ]
