# Generated by Django 4.1.2 on 2022-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='haciendodiferencia',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
