# Generated by Django 4.1.2 on 2022-12-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(upload_to='entradas/cultura')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaCulturaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='entradas/cultura/galeria')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='entradas.culturatributaria')),
            ],
        ),
    ]
