# Generated by Django 4.1.2 on 2022-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_culturatributaria_galeriaculturatributaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='¡no modificar!', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='culturatributaria',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='¡no modificar!', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='haciendodiferencia',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='¡no modificar!', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='¡no modificar!', null=True, unique=True),
        ),
    ]
