# Generated by Django 4.1.2 on 2022-11-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_rename_galerianoticias_galerianoticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
                ('imagen_principal', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Diferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
                ('imagen_principal', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='galerianoticia',
            old_name='noticia',
            new_name='entrada',
        ),
        migrations.CreateModel(
            name='GaleriaDiferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='entradas.diferencia')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaCongreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='entradas.congreso')),
            ],
        ),
    ]
