from django.contrib import admin
from .models import A094_ManualesDeProcedimientos, A095_EstructuraOrganizativa, A096_SeguimientoDeDocumentos, A097_DescripciónDeFormularios, A098_ReglasDeProcedimiento, A102_EjecucionesPresupuestarias, A103_Estadisticas, A112_DesignaciónDeColaboradores, A113_Planilla, A113_PlanillaArchivos, A114_GastosDeRepresentación, A114_GastosDeRepresentaciónArchivos, A115_informesDeViajesNacionales, A115_informesDeViajesNacionalesResumen, A115_informesDeViajesInternacionales, A115_informesDeViajesInternacionalesResumen, A261_SolicitudDeInformaciónPresentadaALaInstitución, A262_AdjuntosDeSolicitudesResueltasYNegadas, A263_ParticipaciónCiudadana

# Register your models here.

admin.site.register(A094_ManualesDeProcedimientos)
admin.site.register(A095_EstructuraOrganizativa)
admin.site.register(A096_SeguimientoDeDocumentos)
admin.site.register(A097_DescripciónDeFormularios)
admin.site.register(A098_ReglasDeProcedimiento)
admin.site.register(A102_EjecucionesPresupuestarias)
admin.site.register(A103_Estadisticas)
admin.site.register(A112_DesignaciónDeColaboradores)
admin.site.register(A113_Planilla)
admin.site.register(A113_PlanillaArchivos)
admin.site.register(A114_GastosDeRepresentación)
admin.site.register(A114_GastosDeRepresentaciónArchivos)
admin.site.register(A115_informesDeViajesNacionales)
admin.site.register(A115_informesDeViajesNacionalesResumen)
admin.site.register(A115_informesDeViajesInternacionales)
admin.site.register(A115_informesDeViajesInternacionalesResumen)
admin.site.register(A261_SolicitudDeInformaciónPresentadaALaInstitución)
admin.site.register(A262_AdjuntosDeSolicitudesResueltasYNegadas)
admin.site.register(A263_ParticipaciónCiudadana)


