import React from 'react'
import Head from 'next/head'
import Navbar from './elements/Navbar'
import Footer from './elements/Footer'
import Header from './elements/Header'
export default function Layer({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Navbar />
            <main>
                {children}
            </main>

            <Footer />

        </>

    )
}
