# Generated by Django 4.1.2 on 2022-11-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasResoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Memorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/memorias/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/otros/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RevistasTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/revistas-tributaria/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('año', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='año')),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/resoluciones/%Y/%m/%d/')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='publicaciones.categoriasresoluciones')),
            ],
        ),
        migrations.CreateModel(
            name='PonenciasArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/ponencias/%Y/%m/%d/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='publicaciones.ponencia')),
            ],
        ),
    ]
