# Generated by Django 4.1.2 on 2022-11-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_remove_resolucion_categoria_resolucion_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasresoluciones',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
