# Generated by Django 4.1.2 on 2022-11-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_categoriasponencia_ponencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonenciaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/resoluciones/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ponencia',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='ponencia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriasPonencia',
        ),
        migrations.AddField(
            model_name='ponenciaentrada',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='publicaciones.ponencia'),
        ),
    ]
