# Generated by Django 4.1.2 on 2022-11-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_ponenciaentrada_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonenciasArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/ponencias/%Y/%m/%d/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='publicaciones.ponencia')),
            ],
        ),
        migrations.CreateModel(
            name='RevistasTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/revistas-tributaria/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='PonenciaEntrada',
        ),
    ]
