# Generated by Django 4.1.2 on 2022-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_ponenciasarchivos_revistastributaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/memorias/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='uploads/publicaciones/otros/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='ponenciasarchivos',
            name='archivo',
            field=models.FileField(upload_to='uploads/publicaciones/ponencias/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='archivo',
            field=models.FileField(upload_to='uploads/publicaciones/resoluciones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='revistastributaria',
            name='archivo',
            field=models.FileField(upload_to='uploads/publicaciones/revistas-tributaria/%Y/%m/%d/'),
        ),
    ]
