# Generated by Django 4.1.2 on 2022-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A102_EjecucionesPresupuestarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('pdf', models.FileField(upload_to='transparencias/102/pdf')),
                ('cvs', models.FileField(upload_to='transparencias/102/cvs')),
                ('xlsx', models.FileField(upload_to='transparencias/102/xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='A103_Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/103')),
            ],
        ),
        migrations.CreateModel(
            name='A112_DesignaciónDeColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/103')),
            ],
        ),
        migrations.CreateModel(
            name='A114_GastosDeRepresentación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('gastos_de_representación', models.CharField(max_length=200)),
                ('inicio_de_labores', models.DateField()),
                ('objeto_de_gasto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='A114_GastosDeRepresentaciónArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='transparencias/112/pdf')),
                ('cvs', models.FileField(upload_to='transparencias/112/cvs')),
                ('xlsx', models.FileField(upload_to='transparencias/112/xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='A114_Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('Salario_Mensual', models.CharField(max_length=200)),
                ('inicio_de_labores', models.DateField()),
                ('objeto_de_gasto', models.CharField(max_length=200)),
                ('Estatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='A114_PlanillaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='transparencias/112/pdf')),
                ('cvs', models.FileField(upload_to='transparencias/112/cvs')),
                ('xlsx', models.FileField(upload_to='transparencias/112/xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='A115_informesDeViajesInternacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('destino_participación', models.CharField(blank=True, max_length=200)),
                ('fecha_salida', models.DateField(blank=True, max_length=200)),
                ('fecha_regreso', models.DateField(blank=True, max_length=200)),
                ('costo', models.FloatField(blank=True)),
                ('viatico', models.PositiveIntegerField(blank=True)),
                ('informe', models.FileField(blank=True, upload_to='transparencias/115')),
            ],
        ),
        migrations.CreateModel(
            name='A115_informesDeViajesInternacionalesResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo_total', models.FloatField()),
                ('viatico', models.FloatField()),
                ('gran_total', models.FloatField()),
                ('pdf', models.FileField(upload_to='transparencias/115/resumen/pdf')),
                ('cvs', models.FileField(upload_to='transparencias/115/resumen/cvs')),
                ('xlsx', models.FileField(upload_to='transparencias/115/resumen/xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='A115_informesDeViajesNacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('destino_participación', models.CharField(blank=True, max_length=200)),
                ('fecha_salida', models.DateField(blank=True, max_length=200)),
                ('fecha_regreso', models.DateField(blank=True, max_length=200)),
                ('costo', models.FloatField(blank=True)),
                ('viatico', models.PositiveIntegerField(blank=True)),
                ('informe', models.FileField(blank=True, upload_to='transparencias/115')),
            ],
        ),
        migrations.CreateModel(
            name='A115_informesDeViajesNacionalesResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo_total', models.FloatField()),
                ('viatico', models.FloatField()),
                ('gran_total', models.FloatField()),
                ('pdf', models.FileField(upload_to='transparencias/115/resumen/pdf')),
                ('cvs', models.FileField(upload_to='transparencias/115/resumen/cvs')),
                ('xlsx', models.FileField(upload_to='transparencias/115/resumen/xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='A261_SolicitudDeInformaciónPresentadaALaInstitución',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/261')),
            ],
        ),
        migrations.CreateModel(
            name='A262_AdjuntosDeSolicitudesResueltasYNegadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/262')),
            ],
        ),
        migrations.CreateModel(
            name='A263_ParticipaciónCiudadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(blank=True, upload_to='transparencias/263')),
            ],
        ),
        migrations.CreateModel(
            name='A94_ManualesDeProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/94')),
            ],
        ),
        migrations.CreateModel(
            name='A95_EstructuraOrganizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/95')),
            ],
        ),
        migrations.CreateModel(
            name='A96_SeguimientoDeDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/96')),
            ],
        ),
        migrations.CreateModel(
            name='A97_DescripciónDeFormularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/97')),
            ],
        ),
        migrations.CreateModel(
            name='A98_ReglasDeProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('archivo', models.FileField(upload_to='transparencias/98')),
            ],
        ),
    ]
