# Generated by Django 4.1.2 on 2022-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a102_ejecucionespresupuestarias',
            name='cvs',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/102/cvs'),
        ),
        migrations.AlterField(
            model_name='a102_ejecucionespresupuestarias',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/102/pdf'),
        ),
        migrations.AlterField(
            model_name='a102_ejecucionespresupuestarias',
            name='xlsx',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/102/xlsx'),
        ),
    ]
