# Generated by Django 4.1.2 on 2022-11-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A94_ManualesDeProcedimientos',
            new_name='A094_ManualesDeProcedimientos',
        ),
        migrations.RenameModel(
            old_name='A95_EstructuraOrganizativa',
            new_name='A095_EstructuraOrganizativa',
        ),
        migrations.RenameModel(
            old_name='A96_SeguimientoDeDocumentos',
            new_name='A096_SeguimientoDeDocumentos',
        ),
        migrations.RenameModel(
            old_name='A97_DescripciónDeFormularios',
            new_name='A097_DescripciónDeFormularios',
        ),
        migrations.RenameModel(
            old_name='A98_ReglasDeProcedimiento',
            new_name='A098_ReglasDeProcedimiento',
        ),
        migrations.RenameModel(
            old_name='A114_Planilla',
            new_name='A113_Planilla',
        ),
        migrations.RenameModel(
            old_name='A114_PlanillaArchivos',
            new_name='A113_PlanillaArchivos',
        ),
    ]
