# Generated by Django 4.1.2 on 2022-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0002_alter_a102_ejecucionespresupuestarias_cvs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a115_informesdeviajesinternacionales',
            old_name='destino_participación',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='a115_informesdeviajesnacionales',
            old_name='destino_participación',
            new_name='destino',
        ),
        migrations.AddField(
            model_name='a115_informesdeviajesinternacionales',
            name='participación',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='a115_informesdeviajesnacionales',
            name='participación',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a263_participaciónciudadana',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/263'),
        ),
    ]
