# Generated by Django 4.1.2 on 2022-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0003_rename_destino_participación_a115_informesdeviajesinternacionales_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a263_participaciónciudadana',
            name='archivo',
        ),
        migrations.AddField(
            model_name='a263_participaciónciudadana',
            name='ver',
            field=models.URLField(blank=True, null=True),
        ),
    ]
