# Generated by Django 4.1.2 on 2022-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0003_remove_a115_informesdeviajesinternacionalesresumen_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='destino_participación',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='fecha_regreso',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='fecha_salida',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/115'),
        ),
        migrations.AlterField(
            model_name='a115_informesdeviajesnacionales',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='a263_participaciónciudadana',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='transparencias/263'),
        ),
    ]
