# Generated by Django 4.1.2 on 2022-12-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0004_remove_a263_participaciónciudadana_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a263_participaciónciudadana',
            old_name='ver',
            new_name='link',
        ),
    ]
