# Generated by Django 4.1.2 on 2022-12-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0007_alter_a00staticos_archivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A00Staticos',
            new_name='A00Estaticos',
        ),
    ]
