# Generated by Django 4.1.2 on 2022-12-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0008_rename_a00staticos_a00estaticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='a00estaticos',
            name='articulo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
