# Generated by Django 4.1.2 on 2022-12-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0009_a00estaticos_articulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a00estaticos',
            options={'ordering': ('-pk',)},
        ),
    ]
