# Generated by Django 4.1.2 on 2022-12-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0011_alter_a00estaticos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a00estaticos',
            options={},
        ),
    ]
